@baseUrl = http://localhost:3000
# @baseUrl = https://osia-api-production.up.railway.app

### registrar a un nuevo usuario
POST {{baseUrl}}/auth/register
Content-Type: application/json

{
    "name" : "Dan",
    "surname" : "Goldman",
    "email" : "ipolonuer@gmail.com",
    "phone" : "1138021709",
    "password" : "osia"
}

### login
POST {{baseUrl}}/auth/login
Content-Type: application/json

{
    "email" : "goldmandan8@gmail.com",
    "password" : "osia"
}

### obtener todos los usuarios
GET {{baseUrl}}/users/all

### borrar un usuario
DELETE {{baseUrl}}/users
Content-Type: application/json

{
    "email" : ""
}

### agregar una radiografia
POST {{baseUrl}}/radiographies/upload
Content-Type: application/json

{
    "imageRoute" : "./public/images/1",
    "userId" : "1"
}

### obteniendo las radiografias de un usuario
GET {{baseUrl}}/radiographies/all
Content-Type: application/json

{
    "userId" : "1"
}

### borrando una radiografia
DELETE {{baseUrl}}/radiographies/delete
Content-Type: application/json

{
    "imageRoute" : ""
}

