@baseUrl = http://localhost:3000
# @baseUrl = https://osia-api-production.up.railway.app

### Logout
GET {{baseUrl}}/auth/logout

### Registrar
POST {{baseUrl}}/auth/register
Content-Type: application/json

{
    "name" : "",
    "surname" : "",
    "email" : "",
    "phone" : "",
    "password" : ""
}

### Login
POST {{baseUrl}}/auth/login
Content-Type: application/json

{
    "email" : "",
    "password" : ""
}

### Verificar si esta loggeado
POST {{baseUrl}}/auth/isLoggedIn
Authorization: Bearer 

### Verificar si no esta loggeado
POST {{baseUrl}}/auth/isNotLoggedIn
Authorization: Bearer 

### Solicitar un nuevo par de JWT
POST {{baseUrl}}/auth/refresh-token
Cookie: refresh_token=

### Obtener todas las radiografias de un usuario
GET {{baseUrl}}/radiographies/all
Authorization: Bearer 

### Obtener el resultado de una radiografía
GET {{baseUrl}}/radiographies/:id/result
Authorization: Bearer 

### Eliminar una radiografía
DELETE {{baseUrl}}/radiographies/:id
Authorization: Bearer 

### Obtener el nombre completo de un usuario
GET {{baseUrl}}/users/full-name
Authorization: Bearer 

### Obtener la información de un usuario
GET {{baseUrl}}/users/info
Authorization: Bearer 

### Renderizar la página de reestablecer contraseña
GET {{baseUrl}}/users/reset-password/:id/:token

### Enviar mail de reestablecimiento de contraseña
POST {{baseUrl}}/users/forgot-password
Content-Type: application/json

{
    "email" : ""
}

### Reestablecer contraseña
POST {{baseUrl}}/users/reset-password/:id/:token
Content-Type: application/json

{
    "password" : "",
    "password2" : ""
}